// Copyright (c) 2025 Kodama Project. All rights reserved.
// Released under the GPL-3.0 license as described in the file LICENSE.
// Authors: Kokic (@kokic)

use std::collections::HashMap;

use camino::{Utf8Path, Utf8PathBuf};
use eyre::{eyre, WrapErr};
use serde::Serialize;

use crate::{
    compiler::{self, section::HTMLContent},
    config, entry::HTMLMetaData, environment,
    slug::Slug,
};

#[derive(clap::Args)]
pub struct SnipCommand {
    /// Path to the configuration file (e.g., "Kodama.toml").
    /// When omitted, `--section` searches for the config from the current
    /// directory upward, and `--katex`/`--inline-section` write to `.vscode/`
    /// in the current directory.
    #[arg(short, long)]
    config: Option<String>,

    /// Generate `.vscode/katex.code-snippets`.
    #[arg(short, long)]
    katex: bool,

    /// Generate `.vscode/section.code-snippets`.
    #[arg(short, long)]
    section: bool,

    /// Generate `.vscode/inline-section.code-snippets`.
    #[arg(short, long)]
    inline_section: bool,
}

#[derive(Serialize)]
struct Snippet {
    scope: &'static str,
    prefix: String,
    body: [String; 1],
    description: String,
}

impl Snippet {
    fn new(scope: &'static str, prefix: String, body: [String; 1], description: String) -> Self {
        Self {
            scope,
            prefix,
            body,
            description,
        }
    }

    fn md(prefix: String, body: [String; 1], description: String) -> Self {
        Self::new("markdown", prefix, body, description)
    }
}

/// This function invokes the [`environment::init_environment`] function to initialize the environment
pub fn snip(command: &SnipCommand) -> eyre::Result<()> {
    let config_path = command
        .config
        .as_deref()
        .or_else(|| command.section.then_some(config::DEFAULT_CONFIG_PATH));

    let root = if let Some(path) = config_path {
        environment::init_environment(Utf8Path::new(path), environment::BuildMode::Serve)?;
        environment::root_dir()
    } else {
        Utf8PathBuf::from(".")
    };

    if command.section {
        section_snippets()?;
    }

    // Unlike `section_snippets`, these two write static snippet files from
    // bundled resources and only need `root` as the write target, without
    // relying on config or the environment.
    if command.katex {
        katex_snippets(&root)?;
    }

    if command.inline_section {
        inline_section_snippets(&root)?;
    }

    Ok(())
}

fn section_snippets() -> eyre::Result<()> {
    let indexes = refresh_section_indexes()?;

    let snippets: HashMap<&str, Snippet> = indexes
        .iter()
        .filter_map(|(slug, metadata)| {
            let slug_str = slug.as_str();
            let title = metadata.title()?.remove_all_tags();
            let prefix = format!("{title} [{slug_str}]");
            let ext = metadata.ext()?;
            let trees_dir = environment::trees_dir_without_root();
            let url = format!("/{}/{}.{}", trees_dir, slug_str, ext);

            // We assume that the markdown editor used by the user
            // supports link label names that contain spaces
            let body = [format!("[{title}]: {url}")];
            let description = metadata
                .taxon()
                .and_then(HTMLContent::as_str)
                .unwrap_or("")
                .to_string();

            Some((slug_str, Snippet::md(prefix, body, description)))
        })
        .collect();

    let snippets_path = environment::root_dir()
        .join(".vscode")
        .join("section.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    let serialized = serde_json::to_string_pretty(&snippets)
        .wrap_err_with(|| eyre!("failed to serialize snippets to JSON"))?;
    std::fs::write(&snippets_path, serialized)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}

fn refresh_section_indexes() -> eyre::Result<HashMap<Slug, HTMLMetaData>> {
    environment::ensure_cache_version()?;
    let trees_dir = environment::trees_dir();
    let workspace = compiler::all_trees_source(trees_dir.as_path())
        .wrap_err_with(|| eyre!("failed to scan trees dir `{}` for snippets", trees_dir))?;
    compiler::refresh_indexes(&workspace, None)
        .wrap_err("failed to refresh in-memory section indexes")
}

fn katex_snippets(root: &Utf8Path) -> eyre::Result<()> {
    let snippets_path = root.join(".vscode").join("katex.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    // Generated by: https://github.com/kodama-community/vscode-katex-snippets
    let json = include_str!("../include/katex-snippets.json");
    std::fs::write(&snippets_path, json)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}

fn inline_section_snippets(root: &Utf8Path) -> eyre::Result<()> {
    let snippets_path = root.join(".vscode").join("inline-section.code-snippets");
    environment::create_parent_dirs(&snippets_path);

    let json = include_str!("../include/inline-section-snippets.json");
    std::fs::write(&snippets_path, json)
        .wrap_err_with(|| eyre!("failed to write snippets to `{}`", snippets_path))?;

    Ok(())
}
