// Copyright (c) 2025 Kodama Project. All rights reserved.
// Released under the GPL-3.0 license as described in the file LICENSE.
// Authors: Kokic (@kokic), Alias Qli (@AliasQli), Spore (@s-cerevisiae)

use std::collections::{HashMap, HashSet};

use eyre::{eyre, WrapErr};

use crate::{
    environment,
    slug::{SectionKind, Slug},
};

use super::section::UnresolvedSection;
use super::{
    compile_from_shallows,
    incremental::{dirty_source_slugs, source_relative_path},
    inline_typst, parse_source_sections,
    stale::cleanup_stale_slug_artifacts,
    write_entry_cache, CompileOutputs, DirtySet, ParsedSections, SourceCache, Workspace,
};

#[derive(Default)]
pub struct ServeCompileSession {
    initialized: bool,
    shallows: HashMap<Slug, UnresolvedSection>,
    source_sections: HashMap<Slug, Vec<Slug>>,
}

impl ServeCompileSession {
    pub fn is_initialized(&self) -> bool {
        self.initialized
    }

    pub fn compile_full(
        &mut self,
        workspace: Workspace,
        outputs: CompileOutputs,
    ) -> eyre::Result<()> {
        let stale_slugs = cleanup_stale_slug_artifacts(&workspace)
            .wrap_err("failed to clean stale slug artifacts")?;
        let (shallows, source_sections) = super::collect_shallows_with_sources(&workspace, None)?;
        self.shallows = shallows;
        self.source_sections = source_sections;
        self.initialized = true;
        compile_from_shallows(&workspace, &self.shallows, None, outputs, stale_slugs)
    }

    pub fn compile_incremental(
        &mut self,
        workspace: Workspace,
        dirty_paths: &DirtySet,
        outputs: CompileOutputs,
    ) -> eyre::Result<()> {
        let stale_slugs = cleanup_stale_slug_artifacts(&workspace)
            .wrap_err("failed to clean stale slug artifacts")?;

        let removed_sources: Vec<Slug> = self
            .source_sections
            .keys()
            .copied()
            .filter(|source_slug| !workspace.slug_exts.contains_key(source_slug))
            .collect();
        for source_slug in removed_sources {
            if let Some(slugs) = self.source_sections.remove(&source_slug) {
                for slug in slugs {
                    self.shallows.remove(&slug);
                }
            }
        }

        let dirty_slugs = dirty_source_slugs(&workspace, dirty_paths);
        let mut parse_targets: HashSet<Slug> = dirty_slugs.clone();

        for (&slug, &kind) in &workspace.slug_exts {
            if self.needs_refresh(slug, kind) {
                parse_targets.insert(slug);
            }
        }

        let needs_full_write = parse_targets.iter().any(|slug| !dirty_slugs.contains(slug));

        inline_typst::begin_inline_batch();
        let mut parsed: Vec<(Slug, ParsedSections, SourceCache)> = Vec::new();
        for slug in parse_targets {
            let Some(&kind) = workspace.slug_exts.get(&slug) else {
                continue;
            };
            let relative_path = source_relative_path(slug, kind);
            let entry_path = environment::entry_file_path(relative_path.as_path());
            let sections = parse_source_sections(slug, kind)?;
            let source_meta = environment::relative_source_meta(&relative_path);
            parsed.push((
                slug,
                sections,
                SourceCache {
                    entry_path,
                    source_meta,
                },
            ));
        }

        // Compile all freshly parsed inline formulas in one batch, then resolve
        // their placeholders and write the entry caches.
        let results = inline_typst::compile_inline_batch();
        for (source_slug, mut sections, cache) in parsed {
            for (_, section) in &mut sections {
                inline_typst::resolve_inline_typst_section(section, &results);
            }
            write_entry_cache(cache.entry_path.as_path(), &sections, cache.source_meta)?;

            if let Some(previous_slugs) = self.source_sections.remove(&source_slug) {
                for previous_slug in previous_slugs {
                    self.shallows.remove(&previous_slug);
                }
            }

            let produced_slugs: Vec<Slug> = sections
                .iter()
                .map(|(section_slug, _)| *section_slug)
                .collect();
            for (section_slug, section) in sections {
                if let Some(owner) = self.slug_owner(section_slug) {
                    if owner != source_slug {
                        return Err(eyre!(
                            "section slug collision: `{}` is generated by both `{}` and `{}`",
                            section_slug,
                            owner,
                            source_slug
                        ));
                    }
                }
                self.shallows.insert(section_slug, section);
            }
            self.source_sections.insert(source_slug, produced_slugs);
        }
        self.initialized = true;

        compile_from_shallows(
            &workspace,
            &self.shallows,
            if needs_full_write {
                None
            } else {
                Some(dirty_paths)
            },
            outputs,
            stale_slugs,
        )
    }

    pub fn rewrite_all_from_memory(&mut self, outputs: CompileOutputs) -> eyre::Result<()> {
        // Global/template/theme changes can require re-emitting all pages,
        // but they don't require reparsing source trees.
        let workspace = Workspace {
            slug_exts: HashMap::new(),
        };
        compile_from_shallows(&workspace, &self.shallows, None, outputs, HashSet::new())
    }

    fn needs_refresh(&self, slug: Slug, kind: SectionKind) -> bool {
        if !self.source_sections.contains_key(&slug) {
            return true;
        }
        let Some(shallow) = self.shallows.get(&slug) else {
            return true;
        };
        let expected_suffix = environment::suffix_for_kind(kind);
        shallow
            .ext()
            .map(|value| value != expected_suffix.as_str())
            .unwrap_or(true)
    }

    fn slug_owner(&self, slug: Slug) -> Option<Slug> {
        self.source_sections
            .iter()
            .find_map(|(source_slug, slugs)| slugs.contains(&slug).then_some(*source_slug))
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        compiler::section::{HTMLContent, UnresolvedSection},
        entry::{HTMLMetaData, KEY_EXT, KEY_SLUG},
        ordered_map::OrderedMap,
    };

    use super::*;

    fn shallow(slug: &str, ext: &str) -> UnresolvedSection {
        let mut metadata = OrderedMap::new();
        metadata.insert(KEY_SLUG.to_string(), HTMLContent::Plain(slug.to_string()));
        metadata.insert(KEY_EXT.to_string(), HTMLContent::Plain(ext.to_string()));
        UnresolvedSection {
            metadata: HTMLMetaData(metadata),
            content: HTMLContent::Plain(String::new()),
        }
    }

    #[test]
    fn test_needs_refresh_when_shallow_missing() {
        let session = ServeCompileSession::default();
        assert!(session.needs_refresh(Slug::new("a"), SectionKind::Markdown));
    }

    #[test]
    fn test_needs_refresh_when_extension_matches() {
        let mut session = ServeCompileSession::default();
        session
            .source_sections
            .insert(Slug::new("a"), vec![Slug::new("a")]);
        session.shallows.insert(Slug::new("a"), shallow("a", "md"));
        assert!(!session.needs_refresh(Slug::new("a"), SectionKind::Markdown));
    }

    #[test]
    fn test_needs_refresh_when_extension_differs() {
        let mut session = ServeCompileSession::default();
        session
            .source_sections
            .insert(Slug::new("a"), vec![Slug::new("a")]);
        session.shallows.insert(Slug::new("a"), shallow("a", "md"));
        assert!(session.needs_refresh(Slug::new("a"), SectionKind::Typst));
    }
}
